### ISSUE TITLE
Django connexion can't handle CSRF exempted views

### ISSUE THREAD

**Issue by danielpassy** [buserbrasil/django-connexion#5]
### How to reproduce:
- clone monolito :choreilargado: 
jk

```
@csrf_exempt
@require_POST
def view(request):
    return JsonResponse({}) 
```
declare OpenApi Spec
```
  "/example":
    post:
      summary: 123
      description: 123
      operationId: example.controllers.example
  ```
  
  send a request.
.

results: 
```
WARNING [2022-04-20 10:44:20,824] Forbidden (CSRF cookie not set.): /api/example
```

### Discussion

I'm not familiar with how connexion works with Django, however, in [django/middleware/csrf.py](https://github.com/django/django/blob/7119f40c9881666b6f9b5cf7df09ee1d21cc8344/django/middleware/csrf.py#L426), it's checked if the view is csrf exempt that, due to the use of django conexxion, return False.
